steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/wwibd-server/wwibd-server:latest", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/wwibd-server/wwibd-server:latest"]
