steps:
  # Build the Docker image 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/server-api/server-api', '.']
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/server-api/server-api']